### PR TITLE
Improve code and tests for the newest version of php-jwt

### PR DESCRIPTION
**Pull request by uliandim**
### WHY are these changes introduced?

Because of the vulnerabilities in the older version of php-jwt 

https://snyk.io/vuln/composer:firebase%2Fphp-jwt

## Type of change

- [x] Major: Vulnerability fix

## Checklist

- [x] Updated the composer.json file
- [x] Fixed tests
- [x] Small fix in the decode method

### CODE REVIEW

**Comment by ConstantBqt** [comment]
+1 to this vulnerability fix

**Comment by uliandim** [comment]
Rebased with main, made additional tests fixes, CLA signed. Waiting for an approval 🤷‍♂️

**Comment by OwenMelbz** [comment]
+99999999999999

**Comment by crumb1e** [comment]
+1,  please can this be merged!

**Comment by ConstantBqt** [comment]
The code is not reviewed by learn-libs-superteam. Could we add paulomarg or teddyhwang as reviewers ?

**Comment by uliandim** [comment]
> The code is not reviewed by learn-libs-superteam. Could we add paulomarg or teddyhwang as reviewers ?

I cannot add them because learn-libs-superteam is the the code owner and this can be the only reviewer :(

**Pull request merged**
